name: Push to Docker Hub

on: [push]

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: c4dt/grafana-matrix:latest

